# Generated by Django 5.2.4 on 2025-07-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passby',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
