# Generated by Django 5.2.4 on 2025-07-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_passby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passby',
        ),
    ]
