# Generated by Django 5.2.4 on 2025-07-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_student_city_remove_student_passby'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='lahore', max_length=50),
            preserve_default=False,
        ),
    ]
